server:
  port: 8081

spring:
  application:
    name: springboot-k8s-crud
  datasource:
    url: jdbc:mysql://localhost:3306/orderDemoDb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect