apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment # Name of the deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql  # He said this is selector
  replicas: 3  # This will create 3 pods
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-k8s-crud
          image: springboot-k8s-crud:1.0 # docker image that needs to be used
          ports:
            - containerPort: 8081  # I believe this is the port that configured in application.yml file of docker
          env:   # Setting Environment Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config  # Name given to the configMap yml file. metadata.name
                  key: host

            - name: DB_NAME   # Setting Database name from a ConfigMap
              valueFrom:
                configMapKeyRef:
                  name: db-config   # Name given to the configMap yml file. metadata.name
                  key: dbName

            - name: DB_USERNAME   # Setting Database username from secrets
              valueFrom:
                configMapKeyRef:
                  name: mysql-secrets   # Name given to the secrests yml file. metadata.name
                  key: username

            - name: DB_PASSWORD   # Setting Database password from secrets
              valueFrom:
                configMapKeyRef:
                  name: mysql-secrets   # Name given to the secrests yml file. metadata.name
                  key: password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource(name of the service) kind we are creating
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
  type: NodePort # type of the service.
